import Head from 'next/head'
import Image from 'next/image'
import cold from '../public/images/cold.jpg'
import bg2 from '../public/images/bg-2.png'
import bg3 from '../public/images/bg-3.png'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Amit Group Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className="about_section">
          <div className="container mx-auto py-8 px-9">
            <div className="flex ">
              <div className="w-3/6 m-3">
                <div className="detail-box">
                  <div className="heading_container">
                    <h1 className='font-black text-6xl'>
                      Amit Assessment
                    </h1>
                    <h1 className='text-green-500 text-6xl'>
                      Giải pháp đánh giá nhân lực nhân sự</h1>
                  </div>
                  <p>
                    Hỗ trợ doanh nghiệp tìm được những ứng viên tiềm năng và phù hợp cho vị trí tuyển dụng
                  </p>
                  <div>
                    <button className="m-3 bg-green-400 hover:bg-green-700 text-white font-semibold hover:text-white py-2 px-4 border border-transparent hover:border-transparent rounded">
                      Try it free
                    </button>
                    <button className="m-3 bg-transparent hover:bg-green-500 text-black-400 font-semibold hover:text-white py-2 px-4 border border-black-500 hover:border-transparent rounded">
                      Liên Hệ
                    </button>
                  </div>
                </div>
              </div>
              <div className="w-3/6 m-3">
                <div className="img-box">
                  <Image src={cold} alt="cold picture" className='rounded-lg' />
                </div>
              </div>

            </div>
          </div>
        </section>
        <section className="about_section">
          <div className="container mx-auto py-8 px-9">
            <div className="flex ">
              <div className="w-3/6 m-3">
                <div className="img-box">
                  <Image src={bg2} alt="back ground 2" className='rounded-lg' />
                </div>
              </div>
              <div className="w-3/6 m-3">
                <div className="detail-box">
                  <div className="heading_container">
                    <h2 className=' text-4xl'>
                      Thư viện năng lực yêu cầu cho vị trí tuyển dụng
                    </h2>
                  </div>
                  <p className='font-light leading-8 m-4'>
                    mô tả ngắn
                  </p>
                  <ul>
                    <li className='flex font-thin'>
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 mx-3 w-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                      </svg>
                      Maximize productivity and growth
                    </li>
                    <li className='flex font-thin'>
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 mx-3 w-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                      </svg>
                      Speed past your competition
                    </li>
                    <li className='flex font-thin'>
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 mx-3 w-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                      </svg>
                      Learn the top techniques
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="about_section">
          <div className="container mx-auto py-8 px-9">
            <div className="flex ">
              <div className="w-3/6 m-3">
                <div className="detail-box">
                  <div className="heading_container">
                    <h2 className=' text-4xl'>
                      Đánh giá năng lực ứng viên
                    </h2>
                  </div>
                  <p className='font-light leading-8 m-4'>
                    mô tả ngắn
                  </p>
                  <ul>
                    <li className='flex font-thin'>
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 mx-3 w-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                      </svg>
                      Automated task management workflow
                    </li>
                    <li className='flex font-thin'>
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 mx-3 w-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                      </svg>
                      Detailed analytics for your data
                    </li>
                    <li className='flex font-thin'>
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 mx-3 w-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                      </svg>
                      Some awesome intergrations
                    </li>
                  </ul>
                </div>
              </div>
              <div className="w-3/6 m-3">
                <div className="img-box">
                  <Image src={bg3} alt="back ground 3" className='rounded-lg' />
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="price_section">
          <div className="container mx-auto py-8 px-9">
            <div className='price__title text-center '>
              <h2 className='text-6xl my-3'>Bảng giá</h2>
              <h4 className='text-2xl my-3 pb-8'>Giải pháp AMIT Assessment</h4>
            </div>
            <div className="grid grid-cols-3 gap-4 my-4">
              <div className='price__card border border-black-700 p-12 hover:border-green-500 hover:border-4 hover:scale-110 rounded'>
                <h3 className='card__title text-center text-4xl my-8'>Starter</h3>
                <div className='text-center my-8'>
                  <span className='text-7xl'>$5</span><span className='font-thin'>/ month</span>
                </div>
                <p className='my-8'>
                  Ideal for Startups and Small Companies
                </p>
                <ul>
                  <li className='flex font-normal my-3'>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-green-400 mx-3" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Automated Reporting
                  </li>
                  <li className='flex font-normal my-3'>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-green-400 mx-3" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Faster Processing
                  </li>
                  <li className='flex font-normal my-3'>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-green-400 mx-3" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Customizations
                  </li>
                </ul>
                <button className="w-full bg-transparent hover:bg-green-400 text-green-400 font-semibold hover:text-white py-2 px-4 border border-green-400 hover:border-transparent rounded">
                  Select plan
                </button>
              </div>
              <div className='price__card border border-black-700 p-12 hover:border-green-500 hover:border-4 hover:scale-110 rounded'>
                <h3 className='card__title text-center text-4xl my-8'>Basic</h3>
                <div className='text-center my-8'>
                  <span className='text-7xl'>$15</span><span className='font-thin'>/ month</span>
                </div>
                <p className='my-8'>
                  Ideal for medium-size bussiness to larger businesses
                </p>
                <ul>
                  <li className='flex font-normal my-3'>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-green-400 mx-3" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Everything in Starter
                  </li>
                  <li className='flex font-normal my-3'>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-green-400 mx-3" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    100 Builds
                  </li>
                  <li className='flex font-normal my-3'>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-green-400 mx-3" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Progress Reports
                  </li>
                  <li className='flex font-normal my-3'>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-green-400 mx-3" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Premium Suport
                  </li>
                </ul>
                <button className="w-full bg-transparent hover:bg-green-400 text-green-400 font-semibold hover:text-white py-2 px-4 border border-green-400 hover:border-transparent rounded">
                  Select plan
                </button>
              </div>
              <div className='price__card border border-black-700 p-12 hover:border-green-500 hover:border-4 hover:scale-110 rounded'>
                <h3 className='card__title text-center text-4xl my-8'>Plus</h3>
                <div className='text-center my-8'>
                  <span className='text-7xl'>$15</span><span className='font-thin'>/ month</span>
                </div>
                <p className='my-8'>
                  Ideal for larger and enterprise companies
                </p>
                <ul>
                  <li className='flex font-normal my-3'>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-green-400 mx-3" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Everything in Basic
                  </li>
                  <li className='flex font-normal my-3'>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-green-400 mx-3" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Unlimited Builds
                  </li>
                  <li className='flex font-normal my-3'>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-green-400 mx-3" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Advanced Analytics
                  </li>
                  <li className='flex font-normal my-3'>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-green-400 mx-3" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Company Evaluations
                  </li>
                </ul>
                <button className="w-full bg-transparent hover:bg-green-400 text-green-400 font-semibold hover:text-white py-2 px-4 border border-green-400 hover:border-transparent rounded">
                  Select plan
                </button>
              </div>
            </div>
          </div>
        </section>
        <section className="questions_section">
          <div className="container mx-auto py-8 px-9">
            <div className='price__title text-center '>
              <h2 className='text-6xl my-3'>Câu hỏi thường gặp</h2>
            </div>

            <div className="w-full px-32 ">
              <div className="detail-box p-8 py-8 border border-black-300 my-8 rounded">
                <h2 className='question text-2xl text-green-400 my-4'>How does it work?</h2>
                <p className='text-xl font-extralight'>Ours platform works with your content to provides insight metrics on how you can grow
                  your business and scale your infastucture
                </p>
              </div>
              <div className="detail-box p-8 py-8 border border-black-300 my-8 rounded">
                <h2 className='question text-2xl text-green-400 my-4'>Do you offer team pricing?</h2>
                <p className='text-xl font-extralight'>
                  Yes, wo do! Team pricing is available for any plan. You can take advantage of 30%
                  of for signing up for team pricing of 10 users or more.
                </p>
              </div>
              <div className="detail-box p-8 py-8 border border-black-300 my-8 rounded">
                <h2 className='question text-2xl text-green-400 my-4'>How do i make change and configure my site?</h2>
                <p className='text-xl font-extralight'>You can easily change your site settings inside of your dash by clicking the top right menu
                  and clicking the settings button.
                </p>
              </div>
              <div className="detail-box p-8 py-8 border border-black-300 my-8 rounded">
                <h2 className='question text-2xl text-green-400 my-4'>How do i add a custom domain?</h2>
                <p className='text-xl font-extralight'>You can easily change your site settings inside of your dash by clicking the top right menu
                  and clicking the settings button.
                </p>
              </div>

            </div>
          </div>
        </section>
      </main>

    </div>
  )
}
